apiVersion: v2
name: planetiler-openmaptiles
description: Helm chart to run planetiler-openmaptiles as a Kubernetes Job per install/upgrade (non-blocking)
home: https://github.com/openmaptiles/planetiler-openmaptiles
sources:
  - https://github.com/openmaptiles/planetiler-openmaptiles
  - https://github.com/joachim/planetiler-openmaptiles-helm-chart
keywords:
  - planetiler
  - openmaptiles
  - osm
  - job
  - tiles
  - vector-tiles
kubeVersion: ">=1.23.0-0"
type: application
version: 0.7.0
appVersion: "3.16"
